#!/bin/sh

set -e

case "$(dpkg --print-architecture)" in
	amd64)
		_LINUX_FLAVOURS="amd64"
		_SOURCE="false"
		;;

	i386)
		_LINUX_FLAVOURS="486 686-pae"
		_SOURCE="true"
		;;
esac

lb config noauto \
	--clean \
	--ignore-system-defaults \
	--mode debian \
	--debian-installer live \
	--linux-flavours "${_LINUX_FLAVOURS}" \
	--linux-packages "linux-image linux-headers" \
	--source "${_SOURCE}" \
	--archive-areas "main contrib non-free" \
	--mirror-bootstrap http://127.0.0.1:9999/debian \
	--mirror-chroot-security http://127.0.0.1:9999/security \
	--mirror-binary http://127.0.0.1:9999/debian \
	--mirror-binary-security http://127.0.0.1:9999/security \
"${@}"
